# These are supported funding model platforms

github: [Maxymillion]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: maxymillion
custom: ['buymeacoffee.com/maxymillion']
