import esbuild from "esbuild";
import fs from 'fs';
import process from "process";
import builtins from 'builtin-modules';
import * as dotenv from 'dotenv';

dotenv.config();

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: (prod ? '' : process.env.HOME + process.env.OBSIDIAN_PATH) + 'main.js',
}).then(() => {
	if (!prod) {
		fs.copyFileSync("manifest.json", `${process.env.HOME + process.env.OBSIDIAN_PATH}/manifest.json`);
		fs.copyFileSync("styles.css", `${process.env.HOME + process.env.OBSIDIAN_PATH}/styles.css`);
	}
}).catch(() => process.exit(1));
