name: Create release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Run NPM Install
              run: npm install
            - name: Run NPM Build
              run: npm run build
            - name: Build
              id: build
              run: |
                  mkdir ${{ secrets.PLUGIN_NAME }}
                  cp main.js manifest.json ${{ secrets.PLUGIN_NAME }}
                  zip -r ${{ secrets.PLUGIN_NAME }}.zip ${{ secrets.PLUGIN_NAME }}
                  ls
                  echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
                  VERSION: ${{ github.ref }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload zip file
              id: upload-zip
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./${{ secrets.PLUGIN_NAME }}.zip
                  asset_name: ${{ secrets.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip
                  asset_content_type: application/zip

            - name: Upload main.js
              id: upload-main
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: main.js
                  asset_name: main.js
                  asset_content_type: text/javascript

            - name: Upload manifest.json
              id: upload-manifest
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: manifest.json
                  asset_name: manifest.json
                  asset_content_type: application/json

            -   name: Upload styles.css
                id: upload-styles
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: styles.css
                    asset_name: styles.css
                    asset_content_type: application/css

